/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CBtn: typeof import('./src/components/CBtn.vue')['default']
    CCountDown: typeof import('./src/components/CCountDown.vue')['default']
    CParticle: typeof import('./src/components/CParticle.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
